--[[
  What's Left Localization
  Provides translations for enUS (default), zhCN, zhTW with enUS fallback
]]

local WL_LOCALES = {
  enUS = {
  	APPEARANCE_TOKENS = { "appearance", "appearances" },
    KNOWN_TOKENS = { "already known", "already collected" },
    COLLECTED_TOKENS = { "collected" },
    COLLECTED_PROGRESS_PATTERNS = { "collected%s*%((%d+)%s*/%s*(%d+)%)" },
    PET_TOKENS = { "battle pet", "companion", "pet" },
    TEACHES_TOKENS = { "teaches" },
    SUMMON_TOKENS = { "summon" },
    MOUNT_TOKENS = { "mount", "mounts" },
    TOY_TOKENS = { "toy" },
    USE_TOKENS = { "use:" },
    UNAVAILABLE_PATTERNS = { "available with the release", "available in", "not yet available", "unavailable", "coming soon" },
    BRONZE_TOKENS = { "bronze" },
    UI_BREAKDOWN_TITLE = "Breakdown (%d/%d)",
    UI_SETS_TOTAL_FMT = "Sets Total: %s / %s",
    UI_MOUNTS_TOTAL_FMT = "Mounts Total: %s / %s",
    UI_PETS_TOTAL_FMT = "Pets Total: %s / %s",
    UI_TOYS_TOTAL_FMT = "Toys Total: %s / %s",
	
	UI_GEAR_TOTAL_FMT = "Gear Total: %s / %s",
	
    UI_UNLEARNED_TOTAL = "Unlearned Total",
    UI_APP_TITLE = "What's Left?",
    UI_APP_NAME = "What’s Left",
    UI_SECTION_HIDE_KNOWN = "Hide Known",
    UI_SECTION_HIDE_UNAVAILABLE = "Hide Currently Unavailable",
    UI_LABEL_SETS = "Sets",
    UI_LABEL_MOUNTS = "Mounts",
    UI_LABEL_PETS = "Pets",
    UI_LABEL_TOYS = "Toys",
    UI_COMING_SOON = "Coming soon",
    UI_LOCK_TEXT_LOCKED = "|cffffffffFrame: |cffff5555Locked|r",
    UI_LOCK_TEXT_UNLOCKED = "|cffffffffFrame: |cff88ff88Unlocked|r",
    UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – Changelog",
    POPUP_ARE_YOU_SURE = "Are you sure",
    POPUP_ARE_YOU_UNSURE = "ARE YOU UNSURE?",
    ENSEMBLE_NAME_TOKENS = { "ensemble:", "arsenal:" },
    ENSEMBLE_TIP_TOKENS  = { "collect the appearances" },
    UI_GEAR_TIP_TITLE = "What's Left?",
    UI_GEAR_TIP_DESC  = "Left Click to see what's left to learn.",
	
	ALERT_MISSED_GENERIC = "One of your ensembles missed an item!",
	ALERT_MISSED_COUNT   = "One of your ensembles missed %d appearance%s!",
	ALERT_MISSED_NAMED   = "One of your ensembles missed %d appearance%s: %s",
	PLURAL_S             = "s",
	
	ENS_NOTIFS = "Ensemble Notifications",
	ENS_TOOLTIP = "Enabled: Sound + Raidwarning Popup\nSilenced: Chat only\nDisabled: No alerts",
	ENS_OPT_ENABLED  = "Enabled",
	ENS_OPT_SILENCED = "Silenced",
	ENS_OPT_DISABLED = "Disabled",
	
	
	
	UI_GEAR_TIP_DESC2  = "Right Click to see settings.",
	UI_SETTINGS_TITLE           = "Settings",
    UI_SETTINGS_UNLEARNED_HEADER = "Show Unlearned Totals",
    UI_SETTINGS_UNLEARNED_HINT   = "Show a bar with the total Bronze value of unlearned items at vendors.",
    UI_SETTINGS_PETS_HEADER      = "How many pets?",
    UI_SETTINGS_PETS_HINT1       = "Select the amount of pet you'd like to obtain before hiding.",
    --UI_SETTINGS_PETS_HINT2       = "Currently does not affect filtering.",
    --UI_SETTINGS_COMING_SOON_HINT = "Coming soon; this setting is not active yet.",
    UI_SETTINGS_SCALE_HEADER     = "UI Scale",
    UI_SETTINGS_SCALE_HINT       = "Adjust the size of What’s Left? windows.",
    UI_SETTINGS_SCALE_VALUE_FMT  = "UI Scale: %.2f",
  },
  zhCN = {
	APPEARANCE_TOKENS = { "外观", "外形" },
    KNOWN_TOKENS = { "已经学会", "已收集", "已拥有", "已掌握" },
    COLLECTED_TOKENS = { "已收集", "已收藏" },
    COLLECTED_PROGRESS_PATTERNS = { "已收集%s*%((%d+)%s*/%s*(%d+)%)" },
    PET_TOKENS = { "战斗宠物", "战宠", "宠物", "伙伴" },
    TEACHES_TOKENS = { "教你" },
    SUMMON_TOKENS = { "召唤" },
    MOUNT_TOKENS = { "坐骑" },
    TOY_TOKENS = { "玩具" },
    USE_TOKENS = { "使用：", "使用:" },
    UNAVAILABLE_PATTERNS = { "暂不可用", "上线后开放", "即将推出" },
    BRONZE_TOKENS = { "青铜" },
    UI_BREAKDOWN_TITLE = "已收集统计（%d/%d）",
    UI_SETS_TOTAL_FMT = "套装总计：%s / %s",
    UI_MOUNTS_TOTAL_FMT = "坐骑总计：%s / %s",
    UI_PETS_TOTAL_FMT = "宠物总计：%s / %s",
    UI_TOYS_TOTAL_FMT = "玩具总计：%s / %s",
    UI_UNLEARNED_TOTAL = "未收集总计",
    UI_APP_TITLE = "还剩什么？",
    UI_APP_NAME = "What’s Left",
    UI_SECTION_HIDE_KNOWN = "隐藏已收集",
    UI_SECTION_HIDE_UNAVAILABLE = "隐藏暂不可用",
    UI_LABEL_SETS = "套装",
    UI_LABEL_MOUNTS = "坐骑",
    UI_LABEL_PETS = "宠物",
    UI_LABEL_TOYS = "玩具",
    UI_COMING_SOON = "即将推出",
    UI_LOCK_TEXT_LOCKED = "|cffffffff框体：|cffff5555已锁定|r",
    UI_LOCK_TEXT_UNLOCKED = "|cffffffff框体：|cff88ff88未锁定|r",
    UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – 更新日志",
    ENSEMBLE_NAME_TOKENS = { "套装：", "武器库：", "兵器库：", "军械：" },
    ENSEMBLE_TIP_TOKENS  = { "收集该套", "套装外观", "武装外观" },
    UI_GEAR_TIP_TITLE = "还剩什么？",
    UI_GEAR_TIP_DESC  = "点击查看还有哪些未收集。",
	
	UI_GEAR_TIP_DESC2        = "右键点击打开设置。",
	UI_SETTINGS_TITLE        = "设置",
	UI_SETTINGS_UNLEARNED_HEADER = "显示未学习总计",
	UI_SETTINGS_UNLEARNED_HINT   = "显示商人处所有未学习物品的总铜币价值。",
	UI_SETTINGS_PETS_HEADER      = "需要多少宠物？",
	UI_SETTINGS_PETS_HINT1       = "请选择在隐藏前想要获得的宠物数量。",
	--UI_SETTINGS_PETS_HINT2       = "目前不会影响过滤。",
	--UI_SETTINGS_COMING_SOON_HINT = "即将推出；该选项尚未启用。",
	UI_SETTINGS_SCALE_HEADER     = "界面缩放",
	UI_SETTINGS_SCALE_HINT       = "调整 What's Left? 窗口的大小。",
	UI_SETTINGS_SCALE_VALUE_FMT  = "界面缩放：%.2f",
	
	ALERT_MISSED_GENERIC = "你的某个套装缺少一件外观！",
	ALERT_MISSED_COUNT   = "你的某个套装缺少 %d 个外观%s！",
	ALERT_MISSED_NAMED   = "你的某个套装缺少 %d 个外观%s：%s",
	PLURAL_S             = "个",

	ENS_NOTIFS = "套装通知",
	ENS_TOOLTIP = "启用：声音 + 团队警报提示\n静音：仅聊天\n禁用：无通知",
	ENS_OPT_ENABLED  = "启用",
	ENS_OPT_SILENCED = "静音",
	ENS_OPT_DISABLED = "禁用",
  },
  ruRU = {
	APPEARANCE_TOKENS = { "облик", "облики" },
    KNOWN_TOKENS = { "уже известно", "изучено", "уже изучено" },
    COLLECTED_TOKENS = { "собрано", "собран", "собрана", "собраны", "collected" },
    COLLECTED_PROGRESS_PATTERNS = { "собрано%s*%((%d+)%s*/%s*(%d+)%)","collected%s*%((%d+)%s*/%s*(%d+)%)" },
    PET_TOKENS = { "боевой питомец", "боевые питомцы", "спутник", "спутники", "питомец", "питомцы" },
    TEACHES_TOKENS = { "учит", "обучает" },
    SUMMON_TOKENS = { "призывать" },
    MOUNT_TOKENS = { "транспорт", "mounts" },
    TOY_TOKENS = { "игрушка" },
    USE_TOKENS = { "использование:" },
    UNAVAILABLE_PATTERNS = { "доступно с выходом", "available in", "not yet available", "unavailable", "coming soon" },
    BRONZE_TOKENS = { "бронза" },
    UI_BREAKDOWN_TITLE = "Все (%d/%d)",
    UI_SETS_TOTAL_FMT = "Всего наборов: %s / %s",
    UI_MOUNTS_TOTAL_FMT = "Всего транспорта: %s / %s",
    UI_PETS_TOTAL_FMT = "Всего питомцев: %s / %s",
    UI_TOYS_TOTAL_FMT = "Всего игрушек: %s / %s",
    UI_UNLEARNED_TOTAL = "Всего не изучено",
    UI_APP_TITLE = "What's Left?",
    UI_APP_NAME = "What's Left",
    UI_SECTION_HIDE_KNOWN = "Скрыть известное",
    UI_SECTION_HIDE_UNAVAILABLE = "Скрыть временно недоступное",
    UI_LABEL_SETS = "Наборы",
    UI_LABEL_MOUNTS = "Транспорт",
    UI_LABEL_PETS = "Питомцы",
    UI_LABEL_TOYS = "Игрушки",
    UI_COMING_SOON = "Скоро",
    UI_LOCK_TEXT_LOCKED = "|cffffffffФрейм: |cffff5555Заблокировано|r",
    UI_LOCK_TEXT_UNLOCKED = "|cffffffffФрейм: |cff88ff88Разблокировано|r",
    UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – Список изменений",
    POPUP_ARE_YOU_SURE = "Вы уверены",
    POPUP_ARE_YOU_UNSURE = "ВЫ НЕ УВЕРЕНЫ?",
    ENSEMBLE_NAME_TOKENS = { "комплект:", "арсенал:" },
    ENSEMBLE_TIP_TOKENS  = { "дает иллюзию внешнего вида" },
    UI_GEAR_TIP_TITLE = "Что осталось?",
    UI_GEAR_TIP_DESC  = "Нажмите, чтобы узнать, что вам еще нужно изучить.",
	
	UI_GEAR_TIP_DESC2        = "ПКМ — открыть настройки.",
UI_SETTINGS_TITLE        = "Настройки",
UI_SETTINGS_UNLEARNED_HEADER = "Показывать невыученное",
UI_SETTINGS_UNLEARNED_HINT   = "Показывает панель с общей стоимостью в бронзе всех невыученных предметов у торговца.",
UI_SETTINGS_PETS_HEADER      = "Сколько питомцев?",
UI_SETTINGS_PETS_HINT1       = "Выберите количество питомцев, которое вы хотите получить перед скрытием.",
--UI_SETTINGS_PETS_HINT2       = "Пока не влияет на фильтрацию.",
--UI_SETTINGS_COMING_SOON_HINT = "Скоро будет доступно; настройка пока не активна.",
UI_SETTINGS_SCALE_HEADER     = "Масштаб интерфейса",
UI_SETTINGS_SCALE_HINT       = "Изменяет размер окон What's Left?.",
UI_SETTINGS_SCALE_VALUE_FMT  = "Масштаб: %.2f",
ALERT_MISSED_GENERIC = "В одном из ваших ансамблей отсутствует внешний вид!",
ALERT_MISSED_COUNT   = "В одном из ваших ансамблей отсутствует %d внешний вид%s!",
ALERT_MISSED_NAMED   = "В одном из ваших ансамблей отсутствует %d внешний вид%s: %s",
PLURAL_S             = "а",

ENS_NOTIFS = "Уведомления ансамблей",
ENS_TOOLTIP = "Включено: звук + предупреждение рейда\nТихо: только в чат\nОтключено: без уведомлений",
ENS_OPT_ENABLED  = "Включено",
ENS_OPT_SILENCED = "Тихо",
ENS_OPT_DISABLED = "Отключено",

  },
deDE = {
	APPEARANCE_TOKENS = { "vorlage", "vorlagen", "erscheinungsbild" },
    KNOWN_TOKENS = { "bereits bekannt", "bereits gesammelt", "schon bekannt" },
    COLLECTED_TOKENS = { "gesammelt", "bereits gesammelt" },
    COLLECTED_PROGRESS_PATTERNS = { "gesammelt%s*%((%d+)%s*/%s*(%d+)%)", "collected%s*%((%d+)%s*/%s*(%d+)%)" },
    PET_TOKENS = { "haustier", "haustiere", "begleiter", "kampfhaustier", "kampfhaustiere" },
    TEACHES_TOKENS = { "lehrt", "bringt dir bei", "erteilt dir die fähigkeit" },
    SUMMON_TOKENS = { "beschwört", "beschwören", "herbeirufen" },
    MOUNT_TOKENS = { "reittier", "reittiere", "mount", "mounts" },
    TOY_TOKENS = { "spielzeug", "als spielzeug" },
    USE_TOKENS = { "benutzen:" },
    UNAVAILABLE_PATTERNS = { "verfügbar mit", "nicht verfügbar", "noch nicht erhältlich", "bald verfügbar", "mit der" },
    BRONZE_TOKENS = { "bronze" },
    UI_BREAKDOWN_TITLE = "Alle (%d/%d)",
    UI_SETS_TOTAL_FMT = "Sets gesamt: %s / %s",
    UI_MOUNTS_TOTAL_FMT = "Reittiere gesamt: %s / %s",
    UI_PETS_TOTAL_FMT = "Haustiere gesamt: %s / %s",
    UI_TOYS_TOTAL_FMT = "Spielzeuge gesamt: %s / %s",
    UI_UNLEARNED_TOTAL = "Noch nicht gelernt gesamt",
    UI_APP_TITLE = "What's Left?",
    UI_APP_NAME = "What's Left",
    UI_SECTION_HIDE_KNOWN = "Bekanntes ausblenden",
    UI_SECTION_HIDE_UNAVAILABLE = "Vorübergehend nicht verfügbares ausblenden",
    UI_LABEL_SETS = "Sets",
    UI_LABEL_MOUNTS = "Reittiere",
    UI_LABEL_PETS = "Haustiere",
    UI_LABEL_TOYS = "Spielzeuge",
    UI_COMING_SOON = "Bald™",
    UI_LOCK_TEXT_LOCKED = "|cffffffffFenster: |cffff5555Gesperrt|r",
    UI_LOCK_TEXT_UNLOCKED = "|cffffffffFenster: |cff88ff88Entsperrt|r",
    UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – Changelog",
    POPUP_ARE_YOU_SURE = "Bist du sicher?",
    POPUP_ARE_YOU_UNSURE = "Bist du unsicher?",
    ENSEMBLE_NAME_TOKENS = { "ensemble:", "arsenal:", "rüstungsset:" },
    ENSEMBLE_TIP_TOKENS = { "schaltet das aussehen frei", "schaltet mehrere vorlagen frei" },
    UI_GEAR_TIP_TITLE = "Was fehlt noch?",
    UI_GEAR_TIP_DESC = "Klicke, um zu sehen, was dir noch fehlt.",
	
	UI_GEAR_TIP_DESC2        = "Rechtsklick, um die Einstellungen zu öffnen.",
	UI_SETTINGS_TITLE        = "Einstellungen",
	UI_SETTINGS_UNLEARNED_HEADER = "Ungelernte Gesamtwerte anzeigen",
	UI_SETTINGS_UNLEARNED_HINT   = "Zeigt eine Leiste mit dem gesamten Bronze-Wert aller ungelernter Gegenstände beim Händler.",
	UI_SETTINGS_PETS_HEADER      = "Wie viele Haustiere?",
	UI_SETTINGS_PETS_HINT1       = "Wähle die Anzahl der Haustiere, die du erhalten möchtest, bevor sie ausgeblendet werden.",
	--UI_SETTINGS_PETS_HINT2       = "Hat derzeit keinen Einfluss auf das Filtern.",
	--UI_SETTINGS_COMING_SOON_HINT = "Demnächst verfügbar; diese Einstellung ist noch nicht aktiv.",
	UI_SETTINGS_SCALE_HEADER     = "UI-Skalierung",
	UI_SETTINGS_SCALE_HINT       = "Passe die Größe der What's Left?-Fenster an.",
	UI_SETTINGS_SCALE_VALUE_FMT  = "UI-Skalierung: %.2f",
	
	ALERT_MISSED_GENERIC = "Eines deiner Ensembles fehlt ein Erscheinungsbild!",
ALERT_MISSED_COUNT   = "Einem deiner Ensembles fehlen %d Erscheinungsbild%s!",
ALERT_MISSED_NAMED   = "Einem deiner Ensembles fehlen %d Erscheinungsbild%s: %s",
PLURAL_S             = "er",

ENS_NOTIFS = "Ensemble-Benachrichtigungen",
ENS_TOOLTIP = "Aktiviert: Sound + Raidwarnung\nStumm: Nur Chat\nDeaktiviert: Keine Benachrichtigungen",
ENS_OPT_ENABLED  = "Aktiviert",
ENS_OPT_SILENCED = "Stumm",
ENS_OPT_DISABLED = "Deaktiviert",
},
esES = {
	APPEARANCE_TOKENS = { "apariencia", "apariencias" },
  KNOWN_TOKENS = { "ya conocido", "ya coleccionado" },
    COLLECTED_TOKENS = { "conseguidos" },
    COLLECTED_PROGRESS_PATTERNS = { "coleccionado%s*%((%d+)%s*/%s*(%d+)%)" },
    PET_TOKENS = { "mascota de duelo", "compañero", "mascota" },
    TEACHES_TOKENS = { "enseña" },
    SUMMON_TOKENS = { "invoca" },
    MOUNT_TOKENS = { "montura", "monturas" },
    TOY_TOKENS = { "juguete" },
    USE_TOKENS = { "usa:" },
    UNAVAILABLE_PATTERNS = { "disponible con el lanzamiento", "disponible en", "aún no disponible", "no disponible", "pronto" },
    BRONZE_TOKENS = { "bronce" },
    UI_BREAKDOWN_TITLE = "Desgloce (%d/%d)",
    UI_SETS_TOTAL_FMT = "Total de conjuntos: %s / %s",
    UI_MOUNTS_TOTAL_FMT = "Total de monturas: %s / %s",
    UI_PETS_TOTAL_FMT = "Total de mascotas: %s / %s",
    UI_TOYS_TOTAL_FMT = "Total de juguetes: %s / %s",
    UI_UNLEARNED_TOTAL = "Total sin aprender",
    UI_APP_TITLE = "Qué falta?",
    UI_APP_NAME = "Qué falta?",
    UI_SECTION_HIDE_KNOWN = "Esconder Conocidos",
    UI_SECTION_HIDE_UNAVAILABLE = "Esconder no disponibles",
    UI_LABEL_SETS = "Conjutos",
    UI_LABEL_MOUNTS = "Monturas",
    UI_LABEL_PETS = "Mascotas",
    UI_LABEL_TOYS = "Juguetes",
    UI_COMING_SOON = "Pronto",
    UI_LOCK_TEXT_LOCKED = "|cffffffffFrame: |cffff5555Locked|r",
    UI_LOCK_TEXT_UNLOCKED = "|cffffffffFrame: |cff88ff88Unlocked|r",
    UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – Log de cambios",
    POPUP_ARE_YOU_SURE = "Estás seguro?",
    POPUP_ARE_YOU_UNSURE = "NO ESTÁS SEGURO?",
    ENSEMBLE_NAME_TOKENS = { "indumentaria", "conjunto", "arsenal" },
    ENSEMBLE_TIP_TOKENS  = { "colecciona las apariencias" },
    UI_GEAR_TIP_TITLE = "Qué falta?",
    UI_GEAR_TIP_DESC  = "Click para ver qué falta aprender.",
	
	UI_GEAR_TIP_DESC2        = "Clic derecho para abrir la configuración.",
	UI_SETTINGS_TITLE        = "Opciones",
	UI_SETTINGS_UNLEARNED_HEADER = "Mostrar totales no aprendidos",
	UI_SETTINGS_UNLEARNED_HINT   = "Muestra una barra con el valor total en Bronce de los objetos no aprendidos en los vendedores.",
	UI_SETTINGS_PETS_HEADER      = "¿Cuántas mascotas?",
	UI_SETTINGS_PETS_HINT1       = "Selecciona la cantidad de mascotas que deseas obtener antes de ocultarlas.",
	--UI_SETTINGS_PETS_HINT2       = "Actualmente no afecta al filtrado.",
	--UI_SETTINGS_COMING_SOON_HINT = "Próximamente; esta opción aún no está activa.",
	UI_SETTINGS_SCALE_HEADER     = "Escala de la IU",
	UI_SETTINGS_SCALE_HINT       = "Ajusta el tamaño de las ventanas de What's Left?.",
	UI_SETTINGS_SCALE_VALUE_FMT  = "Escala de la IU: %.2f",
	
	ALERT_MISSED_GENERIC = "¡A uno de tus conjuntos le falta una apariencia!",
ALERT_MISSED_COUNT   = "A uno de tus conjuntos le faltan %d apariencia%s!",
ALERT_MISSED_NAMED   = "A uno de tus conjuntos le faltan %d apariencia%s: %s",
PLURAL_S             = "s",

ENS_NOTIFS = "Notificaciones de conjuntos",
ENS_TOOLTIP = "Activado: Sonido + alerta de banda\nSilenciado: Solo chat\nDesactivado: Sin notificaciones",
ENS_OPT_ENABLED  = "Activado",
ENS_OPT_SILENCED = "Silenciado",
ENS_OPT_DISABLED = "Desactivado",


},
  zhTW = {
	APPEARANCE_TOKENS = { "外觀", "外形" },
    KNOWN_TOKENS = { "已經學會", "已收集", "已擁有", "已掌握" },
    COLLECTED_TOKENS = { "已收集", "已收藏" },
    COLLECTED_PROGRESS_PATTERNS = { "已收集%s*%((%d+)%s*/%s*(%d+)%)" },
    PET_TOKENS = { "戰鬥寵物", "戰寵", "寵物", "夥伴" },
    TEACHES_TOKENS = { "教你" },
    SUMMON_TOKENS = { "召喚" },
    MOUNT_TOKENS = { "坐騎" },
    TOY_TOKENS = { "玩具" },
    USE_TOKENS = { "使用：", "使用:" },
    UNAVAILABLE_PATTERNS = { "暫不可用", "推出時開放", "即將推出" },
    BRONZE_TOKENS = { "青銅" },
    UI_BREAKDOWN_TITLE = "已收集統計（%d/%d）",
    UI_SETS_TOTAL_FMT = "套裝總計：%s / %s",
    UI_MOUNTS_TOTAL_FMT = "坐騎總計：%s / %s",
    UI_PETS_TOTAL_FMT = "寵物總計：%s / %s",
    UI_TOYS_TOTAL_FMT = "玩具總計：%s / %s",
    UI_UNLEARNED_TOTAL = "未收集總計",
    UI_APP_TITLE = "還剩什麼？",
    UI_APP_NAME = "What’s Left",
    UI_SECTION_HIDE_KNOWN = "隱藏已收集",
    UI_SECTION_HIDE_UNAVAILABLE = "隱藏暫不可用",
    UI_LABEL_SETS = "套裝",
    UI_LABEL_MOUNTS = "坐騎",
    UI_LABEL_PETS = "寵物",
    UI_LABEL_TOYS = "玩具",
    UI_COMING_SOON = "即將推出",
    UI_LOCK_TEXT_LOCKED = "|cffffffff框體：|cffff5555已鎖定|r",
    UI_LOCK_TEXT_UNLOCKED = "|cffffffff框體：|cff88ff88未鎖定|r",
    UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – 更新日誌",
    ENSEMBLE_NAME_TOKENS = { "套裝：", "武器庫：", "軍械：" },
    ENSEMBLE_TIP_TOKENS  = { "收集該套", "套裝外觀", "武裝外觀" },
    UI_GEAR_TIP_TITLE = "還剩什麼？",
    UI_GEAR_TIP_DESC  = "點擊查看尚未收集的項目。",
	
	UI_GEAR_TIP_DESC2        = "右鍵點擊以開啟設定。",
	UI_SETTINGS_TITLE        = "設定",
	UI_SETTINGS_UNLEARNED_HEADER = "顯示未學習總計",
	UI_SETTINGS_UNLEARNED_HINT   = "顯示商人所有未學習物品的總銅幣價值。",
	UI_SETTINGS_PETS_HEADER      = "需要多少寵物？",
	UI_SETTINGS_PETS_HINT1       = "請選擇在隱藏前想要取得的寵物數量。",
	--UI_SETTINGS_PETS_HINT2       = "目前不會影響篩選。",
	--UI_SETTINGS_COMING_SOON_HINT = "即將推出；此選項尚未啟用。",
	UI_SETTINGS_SCALE_HEADER     = "介面縮放",
	UI_SETTINGS_SCALE_HINT       = "調整 What's Left? 視窗大小。",
	UI_SETTINGS_SCALE_VALUE_FMT  = "介面縮放：%.2f",
	
	ALERT_MISSED_GENERIC = "你的其中一個套裝缺少外觀！",
ALERT_MISSED_COUNT   = "你的其中一個套裝缺少 %d 個外觀%s！",
ALERT_MISSED_NAMED   = "你的其中一個套裝缺少 %d 個外觀%s：%s",
PLURAL_S             = "個",

ENS_NOTIFS = "套裝通知",
ENS_TOOLTIP = "啟用：音效 + 團隊警告提示\n靜音：僅聊天\n停用：無通知",
ENS_OPT_ENABLED  = "啟用",
ENS_OPT_SILENCED = "靜音",
ENS_OPT_DISABLED = "停用",


  },
  frFR = {
APPEARANCE_TOKENS = { "apparence", "apparences" },
  KNOWN_TOKENS = { "déjà connu", "déjà collectionné" },
  COLLECTED_TOKENS = { "collectionné", "collecté" },
  COLLECTED_PROGRESS_PATTERNS = { "collectionné%s*%((%d+)%s*/%s*(%d+)%)" },
  PET_TOKENS = { "familier de combat", "familier", "compagnon" },
  TEACHES_TOKENS = { "apprend", "enseigne" },
  SUMMON_TOKENS = { "invoque" },
  MOUNT_TOKENS = { "monture", "montures" },
  TOY_TOKENS = { "jouet", "jouets" },
  USE_TOKENS = { "utilise", "utilisation", "utiliser" },
  UNAVAILABLE_PATTERNS = { "disponible lors de la sortie", "disponible dans", "pas encore disponible", "bientôt disponible" },
  BRONZE_TOKENS = { "bronze" },

  UI_BREAKDOWN_TITLE = "Détail (%d/%d)",
  UI_SETS_TOTAL_FMT = "Total des ensembles : %s / %s",
  UI_MOUNTS_TOTAL_FMT = "Total des montures : %s / %s",
  UI_PETS_TOTAL_FMT = "Total des familiers : %s / %s",
  UI_TOYS_TOTAL_FMT = "Total des jouets : %s / %s",
  UI_UNLEARNED_TOTAL = "Total non appris",
  UI_APP_TITLE = "Qu’est-ce qu’il reste ?",
  UI_APP_NAME = "Qu’est-ce qu’il reste",
  UI_SECTION_HIDE_KNOWN = "Masquer les connus",
  UI_SECTION_HIDE_UNAVAILABLE = "Masquer les indisponibles",
  UI_LABEL_SETS = "Ensembles",
  UI_LABEL_MOUNTS = "Montures",
  UI_LABEL_PETS = "Familiers",
  UI_LABEL_TOYS = "Jouets",
  UI_COMING_SOON = "Bientôt disponible",
  UI_LOCK_TEXT_LOCKED = "|cffffffffFenêtre : |cffff5555Verrouillée|r",
  UI_LOCK_TEXT_UNLOCKED = "|cffffffffFenêtre : |cff88ff88Déverrouillée|r",
  UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – Journal des modifications",
  POPUP_ARE_YOU_SURE = "Êtes-vous sûr ?",
  POPUP_ARE_YOU_UNSURE = "ÊTES-VOUS INCERTAIN ?",
  ENSEMBLE_NAME_TOKENS = { "tenue", "arsenal", "ensemble" },
  ENSEMBLE_TIP_TOKENS  = {
    "ajoute les apparences suivantes à votre collection",
    "ajoute ces apparences à votre collection",
  },
  UI_GEAR_TIP_TITLE = "Qu’est-ce qu’il reste ?",
  UI_GEAR_TIP_DESC  = "Cliquez pour voir ce qu’il reste à apprendre.",
  
  UI_GEAR_TIP_DESC2        = "Clique droit pour ouvrir les options.",
UI_SETTINGS_TITLE        = "Options",
UI_SETTINGS_UNLEARNED_HEADER = "Afficher les totaux non appris",
UI_SETTINGS_UNLEARNED_HINT   = "Affiche une barre indiquant la valeur totale en Bronze des objets non appris chez les vendeurs.",
UI_SETTINGS_PETS_HEADER      = "Combien de mascottes ?",
UI_SETTINGS_PETS_HINT1       = "Sélectionnez la quantité de mascotas que deseas obtener avant de les masquer.",
--UI_SETTINGS_PETS_HINT2       = "N’affecte pas encore le filtrage.",
--UI_SETTINGS_COMING_SOON_HINT = "À venir ; cette option n’est pas encore active.",
UI_SETTINGS_SCALE_HEADER     = "Échelle de l’interface",
UI_SETTINGS_SCALE_HINT       = "Ajuste la taille des fenêtres de What's Left?.",
UI_SETTINGS_SCALE_VALUE_FMT  = "Échelle UI : %.2f",

ALERT_MISSED_GENERIC = "L’un de vos ensembles manque une apparence !",
ALERT_MISSED_COUNT   = "L’un de vos ensembles manque %d apparence%s !",
ALERT_MISSED_NAMED   = "L’un de vos ensembles manque %d apparence%s : %s",
PLURAL_S             = "s",

ENS_NOTIFS = "Notifications d’ensembles",
ENS_TOOLTIP = "Activé : Son + Avertissement de raid\nSilencieux : Chat uniquement\nDésactivé : Aucune notification",
ENS_OPT_ENABLED  = "Activé",
ENS_OPT_SILENCED = "Silencieux",
ENS_OPT_DISABLED = "Désactivé",


	},
	itIT = {
	APPEARANCE_TOKENS = { "aspetto", "aspetti", "apparenza" },
  -- Tooltip parsing
  KNOWN_TOKENS = { "già noto", "già appreso", "già raccolto" },
  COLLECTED_TOKENS = { "possedute", "collezionato", "già raccolto" },
  COLLECTED_PROGRESS_PATTERNS = { "raccolti%s*%((%d+)%s*/%s*(%d+)%)" },

  PET_TOKENS = { "mascotte da combattimento", "mascotte", "famiglio", "compagno" },
  TEACHES_TOKENS = { "insegna", "impara a evocare" },
  SUMMON_TOKENS = { "evoca", "evocare" },
  MOUNT_TOKENS = { "cavalcatura", "cavalcature" },
  TOY_TOKENS = { "giocattolo", "giocattoli" },
  USE_TOKENS = { "usa:", "utilizzo:" },

  UNAVAILABLE_PATTERNS = {
    "disponibile con la pubblicazione di",
    "disponibile in",
    "non ancora disponibile",
    "non disponibile",
    "in arrivo",
  },

  BRONZE_TOKENS = { "bronzo" },

  -- UI text
  UI_BREAKDOWN_TITLE = "Dettaglio (%d/%d)",
  UI_SETS_TOTAL_FMT   = "Set totali: %s / %s",
  UI_MOUNTS_TOTAL_FMT = "Cavalcature totali: %s / %s",
  UI_PETS_TOTAL_FMT   = "Mascotte totali: %s / %s",
  UI_TOYS_TOTAL_FMT   = "Giocattoli totali: %s / %s",
  UI_UNLEARNED_TOTAL  = "Totale non appreso",

  UI_APP_TITLE = "Cosa manca?",
  UI_APP_NAME  = "Cosa manca?",
  UI_SECTION_HIDE_KNOWN       = "Nascondi conosciuti",
  UI_SECTION_HIDE_UNAVAILABLE = "Nascondi non disponibili",

  UI_LABEL_SETS   = "Set",
  UI_LABEL_MOUNTS = "Cavalcature",
  UI_LABEL_PETS   = "Mascotte",
  UI_LABEL_TOYS   = "Giocattoli",

  UI_COMING_SOON = "Prossimamente",

  UI_LOCK_TEXT_LOCKED   = "|cffffffffFinestra: |cffff5555Bloccata|r",
  UI_LOCK_TEXT_UNLOCKED = "|cffffffffFinestra: |cff88ff88Sbloccata|r",

  UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – Registro delle modifiche",

  POPUP_ARE_YOU_SURE  = "Sei sicuro?",
  POPUP_ARE_YOU_UNSURE = "NON SEI SICURO?",

  -- Ensembles
  ENSEMBLE_NAME_TOKENS = { "set", "arsenale" },
  ENSEMBLE_TIP_TOKENS  = { "aggiunge le seguenti apparenze alla tua collezione", "aggiunge queste apparenze alla tua collezione" },

  UI_GEAR_TIP_TITLE = "Cosa manca?",
  UI_GEAR_TIP_DESC  = "Clicca per vedere cosa ti manca da imparare.",
  UI_GEAR_TIP_DESC2        = "Clic destro per aprire le impostazioni.",
UI_SETTINGS_TITLE        = "Impostazioni",
UI_SETTINGS_UNLEARNED_HEADER = "Mostra totali non appresi",
UI_SETTINGS_UNLEARNED_HINT   = "Mostra una barra con il valore totale in Bronzo degli oggetti non appresi dai venditori.",
UI_SETTINGS_PETS_HEADER      = "Quante mascotte?",
UI_SETTINGS_PETS_HINT1       = "Seleziona il numero di mascotte che desideri ottenere prima di nasconderle",
--UI_SETTINGS_PETS_HINT2       = "Attualmente non influisce sul filtraggio.",
--UI_SETTINGS_COMING_SOON_HINT = "In arrivo; questa impostazione non è ancora attiva.",
UI_SETTINGS_SCALE_HEADER     = "Scala UI",
UI_SETTINGS_SCALE_HINT       = "Regola la dimensione delle finestre di What's Left?.",
UI_SETTINGS_SCALE_VALUE_FMT  = "Scala UI: %.2f",

ALERT_MISSED_GENERIC = "A uno dei tuoi set manca un'apparenza!",
ALERT_MISSED_COUNT   = "A uno dei tuoi set mancano %d apparenza%s!",
ALERT_MISSED_NAMED   = "A uno dei tuoi set mancano %d apparenza%s: %s",
PLURAL_S             = "e",

ENS_NOTIFS = "Notifiche dei set",
ENS_TOOLTIP = "Abilitato: Suono + Avviso di incursione\nSilenzioso: Solo chat\nDisabilitato: Nessuna notifica",
ENS_OPT_ENABLED  = "Abilitato",
ENS_OPT_SILENCED = "Silenzioso",
ENS_OPT_DISABLED = "Disabilitato",


  
},

ptBR = {
APPEARANCE_TOKENS = { "aparência", "aparências" },
  KNOWN_TOKENS = { "já aprendido", "já coletado" },
  COLLECTED_TOKENS = { "coletado", "colecionado", "já coletado" },
  COLLECTED_PROGRESS_PATTERNS = { "coletado%s*%((%d+)%s*/%s*(%d+)%)" },

  PET_TOKENS = { "mascote de batalha", "mascote", "companheiro" },
  TEACHES_TOKENS = { "ensina", "ensinar" },
  SUMMON_TOKENS = { "invoca", "invocar" },
  MOUNT_TOKENS = { "montaria", "montarias" },
  TOY_TOKENS = { "brinquedo", "brinquedos" },
  USE_TOKENS = { "usar:", "uso:" },

  UNAVAILABLE_PATTERNS = {
    "disponível com o lançamento",
    "disponível em",
    "ainda não disponível",
    "indisponível",
    "em breve",
  },

  BRONZE_TOKENS = { "bronze" },

  -- UI text
  UI_BREAKDOWN_TITLE = "Detalhamento (%d/%d)",
  UI_SETS_TOTAL_FMT   = "Total de conjuntos: %s / %s",
  UI_MOUNTS_TOTAL_FMT = "Total de montarias: %s / %s",
  UI_PETS_TOTAL_FMT   = "Total de mascotes: %s / %s",
  UI_TOYS_TOTAL_FMT   = "Total de brinquedos: %s / %s",
  UI_UNLEARNED_TOTAL  = "Total não aprendido",

  UI_APP_TITLE = "O que falta?",
  UI_APP_NAME  = "O que falta?",
  UI_SECTION_HIDE_KNOWN       = "Ocultar conhecidos",
  UI_SECTION_HIDE_UNAVAILABLE = "Ocultar indisponíveis",

  UI_LABEL_SETS   = "Conjuntos",
  UI_LABEL_MOUNTS = "Montarias",
  UI_LABEL_PETS   = "Mascotes",
  UI_LABEL_TOYS   = "Brinquedos",

  UI_COMING_SOON = "Em breve",

  UI_LOCK_TEXT_LOCKED   = "|cffffffffJanela: |cffff5555Bloqueada|r",
  UI_LOCK_TEXT_UNLOCKED = "|cffffffffJanela: |cff88ff88Desbloqueada|r",

  UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – Registro de alterações",

  POPUP_ARE_YOU_SURE  = "Tem certeza?",
  POPUP_ARE_YOU_UNSURE = "TEM CERTEZA MESMO?",

  -- Ensembles
  ENSEMBLE_NAME_TOKENS = { "indumentária", "arsenal" },
  ENSEMBLE_TIP_TOKENS  = {
    "adiciona as seguintes aparências à sua coleção",
    "adiciona estas aparências à sua coleção",
  },

  UI_GEAR_TIP_TITLE = "O que falta?",
  UI_GEAR_TIP_DESC  = "Clique para ver o que ainda falta aprender.",
  
  UI_GEAR_TIP_DESC2        = "Clique com o botão direito para abrir as opções.",
UI_SETTINGS_TITLE        = "Configurações",
UI_SETTINGS_UNLEARNED_HEADER = "Mostrar totais não aprendidos",
UI_SETTINGS_UNLEARNED_HINT   = "Mostra uma barra com o valor total em Bronze dos itens não aprendidos nos vendedores.",
UI_SETTINGS_PETS_HEADER      = "Quantos mascotes?",
UI_SETTINGS_PETS_HINT1       = "Selecione a quantidade de mascotes que você deseja obter antes de ocultá-las.",
--UI_SETTINGS_PETS_HINT2       = "Atualmente não afeta a filtragem.",
--UI_SETTINGS_COMING_SOON_HINT = "Em breve; esta opção ainda não está ativa.",
UI_SETTINGS_SCALE_HEADER     = "Escala da UI",
UI_SETTINGS_SCALE_HINT       = "Ajusta o tamanho das janelas do What's Left?.",
UI_SETTINGS_SCALE_VALUE_FMT  = "Escala da UI: %.2f",

ALERT_MISSED_GENERIC = "Um dos seus conjuntos está faltando uma aparência!",
ALERT_MISSED_COUNT   = "Um dos seus conjuntos está faltando %d aparência%s!",
ALERT_MISSED_NAMED   = "Um dos seus conjuntos está faltando %d aparência%s: %s",
PLURAL_S             = "s",

ENS_NOTIFS = "Notificações de Conjuntos",
ENS_TOOLTIP = "Ativado: Som + Aviso de Raide\nSilenciado: Apenas chat\nDesativado: Sem notificações",
ENS_OPT_ENABLED  = "Ativado",
ENS_OPT_SILENCED = "Silenciado",
ENS_OPT_DISABLED = "Desativado",


},
esMX = {
	APPEARANCE_TOKENS = { "apariencia", "apariencias" },
  KNOWN_TOKENS = { "ya conocido", "ya coleccionado" },
  COLLECTED_TOKENS = { "conseguidos", "recolectado" },
  COLLECTED_PROGRESS_PATTERNS = { "coleccionado%s*%((%d+)%s*/%s*(%d+)%)" },

  PET_TOKENS = { "mascota de duelo", "mascota", "compañero" },
  TEACHES_TOKENS = { "enseña", "aprende" },
  SUMMON_TOKENS = { "invoca" },
  MOUNT_TOKENS = { "montura", "monturas" },
  TOY_TOKENS = { "juguete", "juguetes" },
  USE_TOKENS = { "uso:", "usar:" },

  UNAVAILABLE_PATTERNS = {
    "disponible con el lanzamiento",
    "disponible en",
    "aún no disponible",
    "no disponible",
    "próximamente",
  },

  BRONZE_TOKENS = { "bronce" },

  UI_BREAKDOWN_TITLE = "Desglose (%d/%d)",
  UI_SETS_TOTAL_FMT   = "Total de conjuntos: %s / %s",
  UI_MOUNTS_TOTAL_FMT = "Total de monturas: %s / %s",
  UI_PETS_TOTAL_FMT   = "Total de mascotas: %s / %s",
  UI_TOYS_TOTAL_FMT   = "Total de juguetes: %s / %s",
  UI_UNLEARNED_TOTAL  = "Total sin aprender",

  UI_APP_TITLE = "Qué falta?",
  UI_APP_NAME  = "Qué falta?",
  UI_SECTION_HIDE_KNOWN       = "Ocultar conocidos",
  UI_SECTION_HIDE_UNAVAILABLE = "Ocultar no disponibles",

  UI_LABEL_SETS   = "Conjuntos",
  UI_LABEL_MOUNTS = "Monturas",
  UI_LABEL_PETS   = "Mascotas",
  UI_LABEL_TOYS   = "Juguetes",

  UI_COMING_SOON = "Próximamente",

  UI_LOCK_TEXT_LOCKED   = "|cffffffffVentana: |cffff5555Bloqueada|r",
  UI_LOCK_TEXT_UNLOCKED = "|cffffffffVentana: |cff88ff88Desbloqueada|r",

  UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – Registro de cambios",

  POPUP_ARE_YOU_SURE  = "Estás seguro?",
  POPUP_ARE_YOU_UNSURE = "NO ESTÁS SEGURO?",

  ENSEMBLE_NAME_TOKENS = { "indumentaria", "conjunto", "arsenal" },
  ENSEMBLE_TIP_TOKENS  = {
    "reúne las apariencias de este conjunto de armadura",
    "reúne las siguientes apariencias para tu colección",
  },

  UI_GEAR_TIP_TITLE = "Qué falta?",
  UI_GEAR_TIP_DESC  = "Haz clic para ver qué te falta aprender.",
  
  UI_GEAR_TIP_DESC2        = "Haz clic derecho para ver la configuración.",
UI_SETTINGS_TITLE        = "Configuración",
UI_SETTINGS_UNLEARNED_HEADER = "Mostrar totales sin aprender",
UI_SETTINGS_UNLEARNED_HINT   = "Muestra una barra con el valor total en Bronce de los objetos sin aprender en los vendedores.",
UI_SETTINGS_PETS_HEADER      = "¿Cuántas mascotas?",
UI_SETTINGS_PETS_HINT1       = "Selecciona la cantidad de mascotas que deseas obtener antes de ocultarlas.",
--UI_SETTINGS_PETS_HINT2       = "Por ahora no afecta al filtrado.",
--UI_SETTINGS_COMING_SOON_HINT = "Muy pronto; esta opción aún no está activa.",
UI_SETTINGS_SCALE_HEADER     = "Escala de la interfaz",
UI_SETTINGS_SCALE_HINT       = "Ajusta el tamaño de las ventanas de What's Left?.",
UI_SETTINGS_SCALE_VALUE_FMT  = "Escala de la interfaz: %.2f",

ALERT_MISSED_GENERIC = "¡A uno de tus conjuntos le falta una apariencia!",
ALERT_MISSED_COUNT   = "A uno de tus conjuntos le faltan %d apariencia%s!",
ALERT_MISSED_NAMED   = "A uno de tus conjuntos le faltan %d apariencia%s: %s",
PLURAL_S             = "s",

ENS_NOTIFS = "Notificaciones de conjuntos",
ENS_TOOLTIP = "Activado: Sonido + alerta de banda\nSilenciado: Solo chat\nDesactivado: Sin notificaciones",
ENS_OPT_ENABLED  = "Activado",
ENS_OPT_SILENCED = "Silenciado",
ENS_OPT_DISABLED = "Desactivado",


},
koKR = {
	APPEARANCE_TOKENS = { "형상", "외형" },
  KNOWN_TOKENS = { "이미 배움" },
  COLLECTED_TOKENS = { "이미 배움", "수집함", "이미 수집함", "수집 완료" },
  COLLECTED_PROGRESS_PATTERNS = { "수집됨%s*%((%d+)%s*/%s*(%d+)%)" },

  PET_TOKENS = { "애완동물 대전", "애완동물", "동반자" },
  TEACHES_TOKENS = { "배움", "배웁니다" },
  SUMMON_TOKENS = { "소환" },
  MOUNT_TOKENS = { "탈것" },
  TOY_TOKENS = { "장난감" },
  USE_TOKENS = { "사용 효과", "사용" },

  UNAVAILABLE_PATTERNS = {
  "아직 사용할 수 없음",     -- still not usable
  "곧 출시",                 -- coming soon
  "출시되면 이용할 수 있습니다", -- available when released
},
  BRONZE_TOKENS = { "청동" },

  UI_BREAKDOWN_TITLE = "세부 항목 (%d/%d)",
  UI_SETS_TOTAL_FMT   = "세트 총합: %s / %s",
  UI_MOUNTS_TOTAL_FMT = "탈것 총합: %s / %s",
  UI_PETS_TOTAL_FMT   = "애완동물 총합: %s / %s",
  UI_TOYS_TOTAL_FMT   = "장난감 총합: %s / %s",
  UI_UNLEARNED_TOTAL  = "미배운 총합",

  UI_APP_TITLE = "남은 것은?",
  UI_APP_NAME  = "남은 것은?",
  UI_SECTION_HIDE_KNOWN       = "이미 배운 항목 숨기기",
  UI_SECTION_HIDE_UNAVAILABLE = "현재 사용할 수 없는 항목 숨기기",

  UI_LABEL_SETS   = "세트",
  UI_LABEL_MOUNTS = "탈것",
  UI_LABEL_PETS   = "애완동물",
  UI_LABEL_TOYS   = "장난감",

  UI_COMING_SOON = "곧 출시",

  UI_LOCK_TEXT_LOCKED   = "|cffffffff창 상태: |cffff5555잠금|r",
  UI_LOCK_TEXT_UNLOCKED = "|cffffffff창 상태: |cff88ff88잠금 해제|r",

  UI_CHANGELOG_TITLE_FMT = "|cff66ccff%s|r – 변경 기록",

  POPUP_ARE_YOU_SURE  = "확실합니까?",
  POPUP_ARE_YOU_UNSURE = "확실하지 않습니까?",

  ENSEMBLE_NAME_TOKENS = { "복장", "병기" },
  ENSEMBLE_TIP_TOKENS  = {
    "형상을 배웁니다",
    "형상을 획득합니다",
    "방어구 세트 형상을 배웁니다",
    "방어구 세트 형상을 획득합니다",
  },

  UI_GEAR_TIP_TITLE = "남은 것은?",
  UI_GEAR_TIP_DESC  = "배워야 할 외형 보기.",
  
  UI_GEAR_TIP_DESC2        = "우클릭으로 설정을 여세요.",
UI_SETTINGS_TITLE        = "설정",
UI_SETTINGS_UNLEARNED_HEADER = "미습득 총합 표시",
UI_SETTINGS_UNLEARNED_HINT   = "상인이 파는 미습득 아이템의 총 브론즈 값을 표시합니다.",
UI_SETTINGS_PETS_HEADER      = "수집할 애완동물 수",
UI_SETTINGS_PETS_HINT1       = "숨기기 전에 획득하고 싶은 애완동물의 수를 선택하세요.",
--UI_SETTINGS_PETS_HINT2       = "현재는 필터링에 영향을 주지 않습니다.",
--UI_SETTINGS_COMING_SOON_HINT = "준비 중입니다. 아직 사용할 수 없습니다.",
UI_SETTINGS_SCALE_HEADER     = "UI 크기",
UI_SETTINGS_SCALE_HINT       = "What's Left? 창의 크기를 조절합니다.",
UI_SETTINGS_SCALE_VALUE_FMT  = "UI 크기: %.2f",

ALERT_MISSED_GENERIC = "일부 연합 장비에 누락된 형상이 있습니다!",
ALERT_MISSED_COUNT   = "일부 연합 장비에 %d개의 형상%s이 누락되었습니다!",
ALERT_MISSED_NAMED   = "일부 연합 장비에 %d개의 형상%s이 누락되었습니다: %s",
PLURAL_S             = "",

ENS_NOTIFS = "연합 장비 알림",
ENS_TOOLTIP = "활성: 소리 + 공격대 경보\n무음: 채팅만 표시\n비활성: 알림 없음",
ENS_OPT_ENABLED  = "활성",
ENS_OPT_SILENCED = "무음",
ENS_OPT_DISABLED = "비활성",


},


}

-- Build locale table with fallback support
local function GetLocaleTable()
  local CURRENT_LOCALE = GetLocale and GetLocale() or "enUS"
  local L = {}
  
  -- Start with enUS as base
  local base = WL_LOCALES.enUS or {}
  for k, v in pairs(base) do L[k] = v end
  
  -- Merge current locale (if exists)
  local cur = WL_LOCALES[CURRENT_LOCALE]
  if cur then
    for k, v in pairs(cur) do L[k] = v end
  end
  
  return L
end

-- Export as global variables
_G.WL_LOCALES = WL_LOCALES
_G.GetLocaleTable = GetLocaleTable
